-- Portable between PostgreSQL and H2 (default dev/test database).

create table app_users (
    id            bigint generated by default as identity primary key,
    username      varchar(50)  not null,
    password_hash varchar(100) not null,
    constraint uk_app_users_username unique (username)
);

create table job_applications (
    id             bigint generated by default as identity primary key,
    owner_username varchar(50)  not null,
    company        varchar(120) not null,
    position       varchar(120) not null,
    status         varchar(20)  not null,
    applied_at     date         not null,
    notes          varchar(2000),
    created_at     timestamp(6) with time zone not null
);

create index idx_job_applications_owner_status on job_applications (owner_username, status);
create index idx_job_applications_owner_applied on job_applications (owner_username, applied_at);

create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    token_hash varchar(64)  not null,
    username   varchar(50)  not null,
    expires_at timestamp(6) with time zone not null,
    revoked    boolean      not null default false,
    constraint uk_refresh_tokens_hash unique (token_hash)
);

create index idx_refresh_tokens_username on refresh_tokens (username);
